#Site
title: Yuxin
description: This is Yuxin' home.
logo: favicon.png
url: Yuxin.github.io
rss_url: /feed.xml

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Comment
comment:
  disqus: kongsong    
  # duoshuo: kongsong
  # youyan: 2122392
  laibili: MTAyMC8yODgzNC81NDA0

# Website analytics
google_analytics: UA-82494501-1
baidu_analytics: 5b31ffbbdc6cff18727f3adf75a03777    #from //hm.baidu.com/hm.js?***

# Author information:
author:
  #resume: /resume
  name: Yu xin     #the name of Blog section
  about_me: I’m Yuxin Zhang, a student from the University of Rochester. This is my online WebQuest about Water Conservation lesson. You can calculate your water footprint and learn ways to conserve water from this lesson, and you will also learn how to make persuasive arguments in this lesson. Please also take a look at the sample poster, and feel free to contact me via email if you have any questions.
 
# Social Links
email:               zhangyuxin17@yeah.com
#google.plus:        username
#twitter:            username
# facebook:            kongsong
# github:              songkong
# stackoverflow:      6438519/song-kong   #from a "http://stackoverflow.com/users/123456/username" link
# linkedin:           kongsong
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile,.sass-cache,.DS_Store,.idea]
